
#* /API/USERS
# get all users
# 
GET http://localhost:3001/api/users
###

# get user by id
GET http://localhost:3001/api/users/668a88517cfb0ee986ac45e2
###

# add a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "overseer",
	"email": "meteorology@gmail.com"
}
###

# update a user
PUT http://localhost:3001/api/users/668a88517cfb0ee986ac45eb
Content-Type: application/json

{
	"username": "apparat",
	"email": "arcadia@gmail.com"
}
###

# delete a user by id
# todo-remove thoughts associated with user
DELETE  http://localhost:3001/api/users/668a88517cfb0ee986ac45e1
###



# */API/USERS/USERiD/FRIENDS/FRIENDiD
# add a friend
POST http://localhost:3001/api/users/668a88517cfb0ee986ac45e2/friends/668a88517cfb0ee986ac45e9
###

# remove a friend
# todo
DELETE http://localhost:3001/api/users/668a88517cfb0ee986ac45e2/friends/668a88517cfb0ee986ac45e3
###



# */API/THOUGHTS
# get all thoughts
GET http://localhost:3001/api/thoughts
###

# get thought by id
GET http://localhost:3001/api/thoughts/668a88517cfb0ee986ac4614
###

# create new thought
POST  http://localhost:3001/api/thoughts
Content-Type: application/json

{
	"thoughtText": "thinking about you's ...",
	"username": "CrookedColours"
}

###

# update a thought by id
PUT http://localhost:3001/api/thoughts/668a88517cfb0ee986ac4618
Content-Type: application/json

{
	"thoughtText": "lk is a thought"	
}
###

# delete a thought
DELETE  http://localhost:3001/api/thoughts/668a88517cfb0ee986ac4614

###




# */API/THOUGHTS/:THOUGHTiD/REACTIONS
# create a reaction stored in a single thought's 'reactions' array field
POST http://localhost:3001/api/thoughts/668a88517cfb0ee986ac4614/reactions
Content-Type: application/json

{

	"reactionBody": "gooey",
	"userName": "GlassAnimals"
}

### 

# pull and remove a reaction by reactionId
DELETE http://localhost:3001/api/thoughts/668a88517cfb0ee986ac4614/reactions
Content-Type: application/json

{
	"reactionId": "668c7fc419fbd97ecd832d32"
}

### 

# ?

# 3 delete