
#* /API/USERS
# get all users
# 
GET http://localhost:3001/api/users
###

# get user by id
GET http://localhost:3001/api/users/668a88517cfb0ee986ac45e0
###

# add a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "forgetit ",
	"email": "shhhhh@gmail.com"
}
###

# update a user
# todo
PUT http://localhost:3001/api/user/:id
Content-Type: application/application/json

{
	"username": "squirellZippers",
	"email": "hell@gmail.com"
}
###

# delete a user by id
# todo
DELETE  http://localhost:3001/api/users/:id
###

# */API/USERS/USERiD/FRIENDS/FRIENDiD
# add a friend
#! stopped right here, doing post routes

POST http://localhost/3001/api/users/:userId/friends/:friendId
Content-Type: application/json

{
	"example": "exampleId",
	"examplefriend": "exampleFriendId"
}
###

# remove a friend
DELETE http://localhost/3001/api/users/:userId/friends/:friendId
###


# */API/THOUGHTS
# get all thoughts
GET http://localhost:3001/api/thoughts
###

# geth thought by id
GET http://localhost:3001/api/thoughts/668a88517cfb0ee986ac4614
###

# create new thought
POST  http://localhost:3001/api/thoughts
Content-Type: application/json

{
	"thoughtText": "shhhhh's ...",
	"username": "tishthegoat"
}

###

# update a thought by id
# todo
PUT http://localhost:3001/api/thoughts/:id
Content-Type: application/json

{
	"thoughtText": "lk is a thought",
	"username": "need to figure out how to this won't change-findbyidandupdate",
	"userId": "need to figure out how to this won't change"
	
}
###

# delete a thought
# todo
DELETE  http://localhost:3001/api/thoughts/:id
###


# */API/THOUGHTS/:THOUGHTiD/REACTIONS
# create a reaction stored in a single thought's 'reactions' array field
# todo
#! stopped right here, doing post routes
POST http://localhost:/3001/api/thoughts/:thoughtId/reactions
### 

# pull and remove a reaction by reactionId
# todo
DELETE HTTP/1.1 http://localhost:/3001/api/thoughts/:thoughtId/reactions
### 

# ?
# 2 get all
# 2 get by id
# 3 post
# 2 put
# 3 delete